"""add premium_expires_at

Revision ID: a596f7a7cf02
Revises: a4982216bca7
Create Date: 2026-03-01 23:25:31.337499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a596f7a7cf02'
down_revision: Union[str, Sequence[str], None] = 'a4982216bca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('premium_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium_expires_at')
    # ### end Alembic commands ###
